INSERT INTO TBL_EXCHANGE_VALUE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_RATE, PORT) VALUES(101, 'USD', 'INR', 75, 8000);
INSERT INTO TBL_EXCHANGE_VALUE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_RATE, PORT) VALUES(102, 'EUR', 'INR', 70, 8000);
INSERT INTO TBL_EXCHANGE_VALUE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_RATE, PORT) VALUES(103, 'RUB', 'INR', 65, 8000);
INSERT INTO TBL_EXCHANGE_VALUE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_RATE, PORT) VALUES(104, 'GBP', 'INR', 60, 8000);